#!/bin/bash
#$ -N ppcan
#$ -cwd
#$ -q gpu
#$ -e error_marchiorot.e
#$ -o output_marchiorot.o
#$ -m bea

source /nfsd/opt/anaconda3/anaconda3.sh
conda activate /nfsd/opt/anaconda3/tensorflow

python -u main.py --mode 1 --alpha 0.25
python -u main.py --mode 1 --alpha 0.5
python -u main.py --mode 1 --alpha 1
python -u main.py --mode 1 --alpha 2
python -u main.py --mode 1 --alpha 4

./run_train.sh
./run_train.sh --ALPHA 0.5
