#!/bin/bash
#$ -N ppcan
#$ -cwd
#$ -q gpu
#$ -e error_marchiorot.e
#$ -o output_marchiorot.o
#$ -m bea

source /nfsd/opt/anaconda3/anaconda3.sh
conda activate /nfsd/opt/anaconda3/tensorflow

python recadvv2.py --alpha 0.125
python recadvv2.py --alpha 0.25
python recadvv2.py --alpha 0.5
python recadvv2.py --alpha 1
python recadvv2.py --alpha 2
python recadvv2.py --alpha 4
python recadvv2.py --alpha 1.0
python recadvv2.py --alpha 2.0
python recadvv2.py --alpha 4.0